version: "3.8"

services:
  backend:
    build: .
    container_name: backend_service
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres_db
    volumes:
      - .:/app
    command: npm run start

  postgres_db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
